name: tamirastesting

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

  steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: set up nodejs
      uses: actions/setup_node@v3

    - name: install dependencies
      uses: npm install

    - name: run testscode
      uses: npm run test

    - name: build project
      uses: npm run build
