name: tamirastesting
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test  -- --watchAll=false

      - name: run build
        run: npm run build

      - name: Upload production build (optional)
        uses: actions/upload-artifact@v3.1.3
        with:
          name: react-build
          path: build/
